Testing the controllers
ridabensalem/blog-app pull request #5
Opened 2023-07-19 12:06 UTC by ridabensalem

in this milestone of blog app we have added the following requirements : 

- Add RSpec as a gem to your project.
- Create a Request spec file for all your controllers.
- Make sure that for each action you check:
- If response status was correct.
- If a correct template was rendered.
- If the response body includes correct placeholder text.

2023-07-19 12:39 UTC, julie-ify requested changes
## Hi @ridabensalem,

Good job so far!

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 12:39 UTC, julie-ify commented on spec/controllers_spec/posts_controller_spec.rb
> +end
- [ ] Kindly indent your tests to enhance readability and look more organized.

- [ ] Kindly write more comprehensive tests, like testing to ensure placeholder text in the post index page.

  ```
  expect(response.body).to include("Welcome to post index page")
  ```

- [ ] Kindly add tests for the post show requests.

2023-07-19 12:39 UTC, julie-ify commented on spec/controllers_spec/posts_controller_spec.rb
> +RSpec.describe PostsController, type: :controller do
- [ ] Kindly note that the tests should be of `type: :request`, not `type: :controller`, as the latter is now somewhat deprecated.

2023-07-19 12:39 UTC, julie-ify commented on spec/controllers_spec/users_controller_spec.rb
> +
- [ ] Kindly indent your tests to enhance readability and look more organized.

- [ ] Kindly write more comprehensive tests, like testing to ensure placeholder text in the user index page.

  ```
  expect(response.body).to include("Welcome to user index page")
  ```

- [ ] Kindly add tests for the user show requests.

2023-07-19 12:39 UTC, julie-ify commented on spec/controllers_spec/users_controller_spec.rb
> +RSpec.describe UsersController, type: :controller do
- [ ] Kindly refactor to use `type: :request`.

2023-07-20 09:52 UTC, mckent05 requested changes
Hi @ridabensalem, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost there](https://user-images.githubusercontent.com/73607512/207265397-5ef597f5-a50c-49b4-8f07-7548b0520e98.gif)


 ## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your code.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 09:52 UTC, mckent05 commented on spec/controllers_spec/users_controller_spec.rb
> +    end
- Good job done so far, but as the previous reviewer suggested, your tests are not complete. According to the project requirements, each action in your controller should be testing for these:
- If response status was correct.
- If a correct template was rendered.
- If the response body includes correct placeholder text.
Please ensure all actions are properly tested, according to the project requirements 👍 👍

2023-07-20 09:52 UTC, mckent05 commented on spec/controllers_spec/posts_controller_spec.rb
> +end
- Good job done so far, but as the previous reviewer suggested, your tests are not complete. According to the project requirements, each action in your controller should be testing for these:
- If response status was correct.
- If a correct template was rendered.
- If the response body includes correct placeholder text.
Please ensure all actions are properly tested, according to the project requirements 👍 👍

2023-07-20 12:42 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @ridabensalem 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media1.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Good code organization and working app
✔️ Added controller specs 📌 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 12:42 UTC, codepantha commented on spec/controllers_spec/posts_controller_spec.rb
> +    end
- [ ] Please write tests for the `show` action on the `PostsController`. These tests should at least do the following:
1. Ensure correct view template is rendered. E.g: `expect(response).to render_template(:show)`
2. Ensure the response body includes the correct placeholder text

2023-07-20 19:38 UTC, closed without merging